/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class yesno extends javax.swing.JFrame {

    /**
     * Creates new form yesno
     */
    public yesno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kraj Dana");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Da li ste sigurni da zelite zakljuciti dan ?");

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("DA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("NE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        
        
        try{
            new FileOutputStream("C:\\Data\\konobar1data.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
         try{
            new FileOutputStream("C:\\Data\\konobar2data.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
          try{
            new FileOutputStream("C:\\Data\\konobar3data.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
           try{
            new FileOutputStream("C:\\Data\\konobar4data.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
            try{
            new FileOutputStream("C:\\Data\\konobar5data.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
             try{
            new FileOutputStream("C:\\Data\\konobar6data.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
              try{
            new FileOutputStream("C:\\Data\\konobar7data.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
               try{
            new FileOutputStream("C:\\Data\\konobar8data.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
                try{
            new FileOutputStream("C:\\Data\\admindata.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
        try{
            new FileOutputStream("C:\\Data\\g.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
        try{
            new FileOutputStream("C:\\Data\\konobar1total.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
        try{
            new FileOutputStream("C:\\Data\\konobar2total.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
        try{
            new FileOutputStream("C:\\Data\\konobar3total.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
        try{
            new FileOutputStream("C:\\Data\\konobar4total.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
        try{
            new FileOutputStream("C:\\Data\\konobar5total.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
        try{
            new FileOutputStream("C:\\Data\\konobar6total.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
        try{
            new FileOutputStream("C:\\Data\\konobar7total.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
        try{
            new FileOutputStream("C:\\Data\\admintotal.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
       try{
            new FileOutputStream("C:\\Data\\prikaz.txt").close();
        }
        catch  (IOException e) {
            e.printStackTrace();
        }
       
          setVisible(false);
              FrameChoose frame = new FrameChoose();
              frame.setVisible(true);
       
       
       
       String mg = "DAN JE USPJESNO NULIRAN";
       JOptionPane.showMessageDialog(null, mg);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
             setVisible(false);
              FrameChoose frame = new FrameChoose();
              frame.setVisible(true);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    
        
        
        
        
        
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yesno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yesno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yesno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yesno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yesno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
